import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

function calcMacros({ weightLbs, dayType }) {
  const weightKg = (weightLbs || 225) / 2.205;
  const bmr = 10 * weightKg + 6.25 * 175 - 5 * 35 + 5;
  const isBJJ = dayType === 'BJJ Training Day';
  const isStrength = dayType === 'Strength Day';
  const isActive = dayType === 'Active Recovery';
  const tdee = isBJJ ? bmr * 1.7 : isStrength ? bmr * 1.6 : isActive ? bmr * 1.4 : bmr * 1.2;
  const calories = Math.round(tdee);
  const proteinG = Math.round(isBJJ || isStrength ? weightLbs * 1.0 : weightLbs * 0.85);
  const fatG = Math.round((calories * 0.27) / 9);
  const carbsG = Math.round(Math.max(50, (calories - proteinG * 4 - fatG * 9) / 4));
  const hydrationOz = Math.round(weightLbs / 2 + (isBJJ ? 32 : 0));
  return { calories, proteinG, carbsG, fatG, hydrationOz };
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { days = 7 } = await req.json().catch(() => ({}));

    const { accessToken } = await base44.asServiceRole.connectors.getConnection('googlecalendar');
    const authHeader = {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    };

    // Get user profile for weight
    const profiles = await base44.entities.UserProfile.list('-created_date', 1);
    const weightLbs = profiles[0]?.zulu_current_weight_lbs || 225;

    // Get upcoming nutrition plans or derive from training sessions
    const createdEvents = [];
    for (let i = 0; i < days; i++) {
      const date = new Date();
      date.setDate(date.getDate() + i);
      const dateStr = date.toISOString().split('T')[0];

      // Check existing nutrition plan
      const plans = await base44.entities.NutritionPlan.filter({ date: dateStr });
      const plan = plans[0];
      const dayType = plan?.day_type || 'Rest Day';
      const macros = calcMacros({ weightLbs, dayType });

      const title = `🥗 Vellera Macros — ${dayType}`;
      const description = [
        `📅 ${dateStr} | ${dayType}`,
        '',
        `🔥 Calories: ${macros.calories} kcal`,
        `🥩 Protein: ${macros.proteinG}g`,
        `🌾 Carbs: ${macros.carbsG}g`,
        `🧈 Fat: ${macros.fatG}g`,
        `💧 Hydration: ${macros.hydrationOz} oz`,
        '',
        dayType === 'BJJ Training Day'
          ? '⚡ Pre-training: 50g fast carbs 90 min before. Post: protein shake within 30 min.'
          : dayType === 'Strength Day'
          ? '💪 Pre-lift: moderate carbs. Post: protein + carbs for recovery.'
          : '🧘 Rest day: lower carbs, keep protein high to preserve muscle.',
        '',
        'Generated by Vellera Training Platform',
      ].join('\n');

      // Create all-day event at 6:00 AM for meal planning reminder
      const eventStart = `${dateStr}T06:00:00`;
      const eventEnd = `${dateStr}T06:30:00`;

      const eventBody = {
        summary: title,
        description,
        start: { dateTime: eventStart, timeZone: 'America/New_York' },
        end: { dateTime: eventEnd, timeZone: 'America/New_York' },
        reminders: {
          useDefault: false,
          overrides: [{ method: 'popup', minutes: 5 }],
        },
        colorId: dayType === 'BJJ Training Day' ? '9' : dayType === 'Strength Day' ? '2' : '8',
      };

      const res = await fetch(
        'https://www.googleapis.com/calendar/v3/calendars/primary/events',
        { method: 'POST', headers: authHeader, body: JSON.stringify(eventBody) }
      );

      if (res.ok) {
        const created = await res.json();
        createdEvents.push({ date: dateStr, eventId: created.id, dayType });
      } else {
        const err = await res.text();
        console.error(`Failed to create event for ${dateStr}:`, err);
      }
    }

    return Response.json({ success: true, events_created: createdEvents.length, events: createdEvents });
  } catch (error) {
    console.error('exportMacrosToCalendar error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});